### PR TITLE
Selected code actions

### PR DESCRIPTION
**Pull request by frankiecerk**
New actions:

- Profile selected code
- Eval selected code and display output in json format in window on the right (did this for parity with vscode plugin, its simple to make this display in the same window as the previous actions instead, can also attach the Eval listener to the process in the run configuration if thats desireable)

Bug fixes:

- check action uses relative path now (that commit got left out of previous prs)
- I get a "UnknwownModule cant be cast as RegoModuleType" error when I download plugin from marketplace, and it prevents me from using the "Create New Project" button on IntelliJ homescreen, commit 2239771 should fix that, please test and let me know

### CODE REVIEW

**Comment by vgramer** [comment]
@frankiecerk I had the error `UnknwownModule cant be cast as RegoModuleType` after adding the customer repository but it was because I went too fast and  I forget to install the plugin and directly open a rego project... After installing the plugin I did not have the error message.

However, the rego project created with the same plugin version... can you tell which version of ide and plugin you have used?

**Comment by frankiecerk** [comment]
> @frankiecerk I had the error `UnknwownModule cant be cast as RegoModuleType` after adding the customer repository but it was because I went too fast and I forget to install the plugin and directly open a rego project... After installing the plugin I did not have the error message.
> 
> However, the rego project created with the same plugin version... can you tell which version of ide and plugin you have used?

Sorry about the delay, the issue with the new project was what you fixed in PR #44, once that is merged to master I will rebase to get rid of that conflict - my fix was different and...worse :)

**Comment by adam-sandor** [comment]
Hello, I'm no Intellij plugin developer but I'd love to see this merged. Is there any way I can help?

**Comment by adam-sandor** [comment]
Thanks @vgramer ! Happy to help test the changes.

**Pull request closed without merging**
