### PR TITLE
Compatibility 223

### LINKED ISSUE #137: Add support for IntelliJ IDEA 2022.3
# What would you like to be added
Support for IntellJ IDEA 2022.3

# Why is this needed
It would be nice to be able to use this plugin in IntellIJ IDEA 2022.3

# Implementation details

### PR DESCRIPTION
**Pull request by vgramer**
# Description
this PR implements the compatibility for the last IDEA version (223).

it also

- bumps dependecies plugin versions and handle java 11 / 17 compatibility
- build.gradle: use default IDEs list provided by the task to verify plugin compatibility
- remove multi platform version build ( eg 212, 221). Iit was relevant at the beginning of the project when the sdk for UI was still in beta, and we were building the plugin against the development version of IDEA. However the SDK for UI is stable, and
we don't build the plugin against the development version. So maintaining multi-platform version build is a PITA. It also make the CI lighter.

 

Fixes #137 

```release-notes
add support for IDEA 2022.3 
```

# Special notes for your reviewer

### CODE REVIEW

**Comment by charlieegan3** [comment]
Hi @vgramer, thanks for your work on this! My java know-how is elementary, but the changes look fine to me at a glance. I have been able to test this with the following steps:

* `./gradlew :plugin:buildPlugin`
* Manually install the plugin at `plugin/build/distributions/opa-idea-plugin-nextVersion-dev.zip` in Goland 2022.3.1.
* See that I can run tests using the IDE test runner
* See that I can run opa fmt from with `CMD+I`
* See that Rego code is highlighted correctly

I don't think that I can create a Rego project since I only have Goland rather than IntelliJ IDEA.

One other thing I noticed was that this test failed locally for me (Darwin, arm64):

```
$ java --version
openjdk 19.0.1 2022-10-18
OpenJDK Runtime Environment Homebrew (build 19.0.1)
OpenJDK 64-Bit Server VM Homebrew (build 19.0.1, mixed mode, sharing)

$ ./gradlew :test 

> Task :test

org.openpolicyagent.ideaplugin.ide.actions.FmtActionTest > test already formatted FAILED
    com.intellij.rt.execution.junit.FileComparisonFailure at FmtActionTest.kt:18

128 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/charlieegan3/Code/opa-idea-plugin/build/reports/tests/test/index.html

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
18 actionable tasks: 6 executed, 12 up-to-date
```

I can see they complete ok on CI, but thought worth mentioning.

Otherwise, unless there's anything else you'd like me to validate, I think we can merge this.

**Comment by vgramer** [comment]
@charlieegan3 thanks for testing! I can not reproduce the error locally. which version of OPA are you using?  moreover, it could be interesting to have the output of the failing test. 

As the code formatting works with the plugin built from the source, I guess testing is due to the environment. IMHO it should not block the release.

**Comment by charlieegan3** [comment]
Hi @vgramer, hmm yes - that would have been good! 😅

```
org.openpolicyagent.ideaplugin.ide.actions.FmtActionTest > test already formatted FAILED
    com.intellij.rt.execution.junit.FileComparisonFailure: already_formatted_after.rego expected:<...array(x)
    }

    else = x[ {
        true
    }]

    arr := [1, 2]

    war...> but was:<...array(x)
    }

    else = x[]

    arr := [1, 2]

    war...>
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.checkResult(CodeInsightTestFixtureImpl.java:1742)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.checkResultByFile(CodeInsightTestFixtureImpl.java:1699)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.lambda$checkResultByFile$26(CodeInsightTestFixtureImpl.java:1219)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:490)
        at com.intellij.openapi.application.impl.ApplicationImpl.invokeAndWait(ApplicationImpl.java:523)
        at com.intellij.testFramework.fixtures.impl.CodeInsightTestFixtureImpl.checkResultByFile(CodeInsightTestFixtureImpl.java:1219)
        at org.openpolicyagent.ideaplugin.ide.actions.FmtActionTest.doTest(FmtActionTest.kt:18)
        at org.openpolicyagent.ideaplugin.ide.actions.FmtActionTest.test already formatted(FmtActionTest.kt:22)
```

My opa version is `0.47.4`. I can see that GitHub is running the tests with v0.40.0. There have been a number of changes to opa fmt since that version which looks to be the cause of the issue.

Crucially, this is now adjusted during the format:

```
--- # old
< else = x {
<       true
< }
--- # new
> else = x
```

The tests pass for me on 0.40.0.

I think makes sense to update the opa version used in CI and this test case. Would you like to do that in this PR?

**Comment by charlieegan3** [comment]
I think that https://github.com/vgramer/opa-idea-plugin/pull/22 should do the trick 🤞

**Comment by vgramer** [comment]
> I think that [vgramer#22](https://github.com/vgramer/opa-idea-plugin/pull/22) should do the trick 🤞

LGTM however i don't have CI when the target branch is not master. can you reopen PR against this repo (open-policy-agent/opa-idea-plugin) once this PR is merge ?

**Comment by charlieegan3** [comment]
Thanks, https://github.com/open-policy-agent/opa-idea-plugin/pull/141 has now been merged to address this.

I can see that the store has updated with new release - thanks!

**Pull request merged**
