### PR TITLE
Make compatible with newer Jetbrains versions

### PR DESCRIPTION
**Pull request by steffann**
Make this plugin compatible with newer JetBrains versions. Tested locally on GoLand 2024.2.

# Description
Simple compatibility marker update.

### CODE REVIEW

**Comment by anderseknert** [comment]
Thanks! I don't have a lot of experience working with this project, but looking back at past upgrades, they've changed a lot more code to accomodate the new changes.

* https://github.com/open-policy-agent/opa-idea-plugin/pull/153
* https://github.com/open-policy-agent/opa-idea-plugin/pull/166
* https://github.com/open-policy-agent/opa-idea-plugin/pull/139
* https://github.com/open-policy-agent/opa-idea-plugin/pull/129

Nothing like that needed here? @vgramer can you PTAL 👍

**Comment by steffann** [comment]
All I can say is “it worked for me” and “it hasn’t crashed yet” ;)

I’m definitely not very experienced here! so don’t take my word for it

**Comment by anderseknert** [comment]
Yeah, that makes two of us then 😊 I can imagine how there are additional checks made when actually publishing the plugin, but @vgramer would know. Let's hope he can chip in.

**Comment by anderseknert** [comment]
Very nice! Looking forward to using this extension once more 🙂

**Comment by marcelmindemann** [comment]
Hi! Are you waiting out for something else before releasing a new version to the Marketplace that includes this change? I would love to install this plugin via the Marketplace instead of building from source.

**Pull request merged**
